---

- name: Install required packages
  apt:
    name: nagios4-core
    state: latest
  when: ansible_distribution == "Ubuntu"

- name: Enable Nagios service
  service:
    name: nagios4
    state: restarted
    enabled: true
  when: ansible_distribution == "Ubuntu"

- name: Install Nagios Dependencies
  apt:
    name:
      - libgd-dev
      - libpng-dev
      - libfreetype6-dev
      - gcc
      - libc6-dev
    state: latest
  when: ansible_distribution == "Ubuntu"
