  - name: Install required packages
    apt:
      name:
        - nagios
        - nagios-nrpe-plugin
        - apache2
        - php
        - libapache2-mod-php
        - php-gd
        - php-pear
        - php-mbstring
        - libssl-dev
    state: present

  - name: Enable Nagios service
    systemd:
      - name: nagios
      - enabled: yes
      - state: started

  - name: Configure service
    template:
      src: nagios.cfg.j2
      dest: /etc/nagios/nagios.cfg
    notify: Restart Nagios

  - name: Allow Apache to start Nagios
    apache2_site:
      name: nagios
      state: enabled

  - name: Restart Nagios
    systemd:
      name: nagios
      state: restarted
